"""initial schema

Revision ID: d0244a1d771a
Revises: 
Create Date: 2026-06-13 13:50:47.396480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd0244a1d771a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sa.Enum('client', 'artist', name='userrole'), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('artist_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('handle', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('specialty', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('response_time_hours', sa.Integer(), nullable=False),
    sa.Column('finishes', sa.JSON(), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=600), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_artist_profiles_handle'), 'artist_profiles', ['handle'], unique=True)
    op.create_table('invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artist_id', sa.Uuid(), nullable=False),
    sa.Column('accepted_by_client_id', sa.Uuid(), nullable=True),
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('contact', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('channel', sa.Enum('email', 'sms', 'link', name='invitechannel'), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('status', sa.Enum('sent', 'accepted', 'expired', name='invitestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by_client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_artist_id'), 'invites', ['artist_id'], unique=False)
    op.create_index(op.f('ix_invites_code'), 'invites', ['code'], unique=True)
    op.create_index(op.f('ix_invites_status'), 'invites', ['status'], unique=False)
    op.create_table('look_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('artist_id', sa.Uuid(), nullable=False),
    sa.Column('look_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('look_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('look_caption', sqlmodel.sql.sqltypes.AutoString(length=240), nullable=False),
    sa.Column('client_photo_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('generated_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('status', sa.Enum('pending', 'viewed', 'quoted', 'declined', name='lookrequeststatus'), nullable=False),
    sa.Column('quote', sqlmodel.sql.sqltypes.AutoString(length=240), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_look_requests_artist_id'), 'look_requests', ['artist_id'], unique=False)
    op.create_index(op.f('ix_look_requests_client_id'), 'look_requests', ['client_id'], unique=False)
    op.create_index(op.f('ix_look_requests_status'), 'look_requests', ['status'], unique=False)
    op.create_table('skin_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tone_tier', sa.Integer(), nullable=False),
    sa.Column('skin_type', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('concerns', sa.JSON(), nullable=True),
    sa.Column('zone_tags', sa.JSON(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skin_profiles_user_id'), 'skin_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skin_profiles_user_id'), table_name='skin_profiles')
    op.drop_table('skin_profiles')
    op.drop_index(op.f('ix_look_requests_status'), table_name='look_requests')
    op.drop_index(op.f('ix_look_requests_client_id'), table_name='look_requests')
    op.drop_index(op.f('ix_look_requests_artist_id'), table_name='look_requests')
    op.drop_table('look_requests')
    op.drop_index(op.f('ix_invites_status'), table_name='invites')
    op.drop_index(op.f('ix_invites_code'), table_name='invites')
    op.drop_index(op.f('ix_invites_artist_id'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_artist_profiles_handle'), table_name='artist_profiles')
    op.drop_table('artist_profiles')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
